apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: openshift-container
    image: openshift/hello-openshift
  initContainers:
  - name: init-mysvc1
    image: busybox
    command: ['sh', '-c', 'until nslookup mysvc1; do echo waiting for  myservice; sleep 2; done;']
    initContainers:
  - name: init-mysvc2
    image: busybox
    command: ['sh', '-c', 'until nslookup mysvc2; do echo waiting for  myservice; sleep 2; done;']

